name: bitcoin_map
description: "A map that displays the places where to spend your bitcoins"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  flutter_map_cancellable_tile_provider: ^3.0.2
  telegram_mini_app: ^0.0.2
  url_launcher: ^6.3.1
  location: ^7.0.1
  share_plus: ^10.1.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/